Importamos librerias necesarias

In [28]:
import pandas as pd

cargamos y mostramos nuestro df

In [29]:
df_coursera_reviews=pd.read_csv('D:Coursera_reviews.csv')
df_coursera_reviews

,reviews,reviewers,date_reviews,rating,course_id
0,"Pretty dry, but I was able to pass with just t...",By Robert S,"Feb 12, 2020",4,google-cbrs-cpi-training
1,would be a better experience if the video and ...,By Gabriel E R,"Sep 28, 2020",4,google-cbrs-cpi-training
2,Information was perfect! The program itself wa...,By Jacob D,"Apr 08, 2020",4,google-cbrs-cpi-training
3,A few grammatical mistakes on test made me do ...,By Dale B,"Feb 24, 2020",4,google-cbrs-cpi-training
4,Excellent course and the training provided was...,By Sean G,"Jun 18, 2020",4,google-cbrs-cpi-training
...,...,...,...,...,...
1454706,g,By Brijesh K,"Aug 25, 2020",5,computer-networking
1454707,.,By Vasavi V M,"Jul 02, 2020",5,computer-networking
1454708,.,By Drishti D,"Jun 20, 2020",5,computer-networking
1454709,.,By FAUSTINE F K,"Jun 07, 2020",5,computer-networking
1454710,G,By Reza S,"Aug 12, 2018",5,computer-networking

Analisis rapido con info y describe

In [30]:
df_coursera_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1454711 entries, 0 to 1454710
Data columns (total 5 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   reviews       1454558 non-null  object
 1   reviewers     1454711 non-null  object
 2   date_reviews  1454711 non-null  object
 3   rating        1454711 non-null  int64
 4   course_id     1454711 non-null  object
dtypes: int64(1), object(4)
memory usage: 55.5+ MB

In [31]:
df_coursera_reviews.describe()

             rating
count  1.454711e+06
mean   4.696649e+00
std    6.983271e-01
min    1.000000e+00
25%    5.000000e+00
50%    5.000000e+00
75%    5.000000e+00
max    5.000000e+00

Calculamos los promedios del rating por curso

In [32]:
# Calcular el promedio del rating agrupado por course_id
df_promedio_rating = df_coursera_reviews.groupby('course_id')['rating'].mean().reset_index()

# Renombrar la columna de promedio del rating
df_promedio_rating = df_promedio_rating.rename(columns={'rating': 'promedio_rating'})
df_promedio_rating

                                             course_id  promedio_rating
0                                 aboriginal-education         4.604061
1                                  access-control-sscp         4.572519
2                                 accounting-analytics         4.426991
3                     accounting-data-analytics-python         3.500000
4                 actualizacion-manejo-diabetes-tipo-2         4.867052
..                                                 ...              ...
599                         womens-health-human-rights         4.894231
600  write-a-feature-length-screenplay-for-film-or-...         4.666667
601                             write-your-first-novel         3.942308
602                              writing-editing-words         4.776699
603                               writing-for-business         4.811780

[604 rows x 2 columns]

Cargamos nuestro otro df a partir del csv con la informacion de los cursos y mostramos

In [33]:
df_coursera_courses=pd.read_csv('D:\SoyHenry\Proyecto Integrador 2\Moocs\Coursera_courses.csv')
df_coursera_courses

,name,institution,course_url,course_id
0,Machine Learning,Stanford University,https://www.coursera.org/learn/machine-learning,machine-learning
1,Indigenous Canada,University of Alberta,https://www.coursera.org/learn/indigenous-canada,indigenous-canada
2,The Science of Well-Being,Yale University,https://www.coursera.org/learn/the-science-of-...,the-science-of-well-being
3,Technical Support Fundamentals,Google,https://www.coursera.org/learn/technical-suppo...,technical-support-fundamentals
4,Become a CBRS Certified Professional Installer...,Google - Spectrum Sharing,https://www.coursera.org/learn/google-cbrs-cpi...,google-cbrs-cpi-training
...,...,...,...,...
618,Accounting Data Analytics with Python,University of Illinois at Urbana-Champaign,https://www.coursera.org/learn/accounting-data...,accounting-data-analytics-python
619,Introduction to Molecular Spectroscopy,University of Manchester,https://www.coursera.org/learn/spectroscopy,spectroscopy
620,Managing as a Coach,"University of California, Davis",https://www.coursera.org/learn/managing-as-a-c...,managing-as-a-coach
621,The fundamentals of hotel distribution,ESSEC Business School,https://www.coursera.org/learn/hotel-distribution,hotel-distribution
622,A Crash Course in Data Science,Johns Hopkins University,https://www.coursera.org/learn/data-science-co...,data-science-course

Eliminamos de nuestro df informacion que no vamos a utilizar para nuestro analisis las url

In [34]:
df_coursera_courses.drop(columns='course_url', axis=1, inplace=True)

In [35]:
df_coursera_courses

,name,institution,course_id
0,Machine Learning,Stanford University,machine-learning
1,Indigenous Canada,University of Alberta,indigenous-canada
2,The Science of Well-Being,Yale University,the-science-of-well-being
3,Technical Support Fundamentals,Google,technical-support-fundamentals
4,Become a CBRS Certified Professional Installer...,Google - Spectrum Sharing,google-cbrs-cpi-training
...,...,...,...
618,Accounting Data Analytics with Python,University of Illinois at Urbana-Champaign,accounting-data-analytics-python
619,Introduction to Molecular Spectroscopy,University of Manchester,spectroscopy
620,Managing as a Coach,"University of California, Davis",managing-as-a-coach
621,The fundamentals of hotel distribution,ESSEC Business School,hotel-distribution
622,A Crash Course in Data Science,Johns Hopkins University,data-science-course

unimos ambos dataframes el que tiene la info de los cursos y el que tiene la de los reviews una vez ya calculado el promedio

In [36]:
df_coursera = pd.merge(df_coursera_courses, df_promedio_rating, on='course_id')

ordenamos por rating y mostramos nuestro dataset

In [37]:
df_coursera.sort_values('promedio_rating', ascending=False, inplace=True)
df_coursera

,name,institution,course_id,promedio_rating
586,Removing Barriers to Change,University of Pennsylvania,removing-barriers-to-change,5.000000
104,Entreprise et changement climatique,ESSEC Business School,entreprise-changement-climatique,5.000000
487,Building Modern Python Applications on AWS,Amazon Web Services,building-modern-python-applications-on-aws,5.000000
50,How to Manage a Remote Team,GitLab,remote-team-management,5.000000
353,El Abogado del Futuro: Legaltech y la Transfor...,Universidad Austral,legaltech,4.968000
...,...,...,...,...
469,The Introduction to Quantum Computing,Saint Petersburg State University,quantum-computing-algorithms,3.309524
499,Social and Economic Networks: Models and Anal...,Stanford University,social-economic-networks,1.000000
506,Curanderismo: Traditional Healing Using Plants,University of New Mexico,curanderismo-plants,1.000000
458,Epigenetic Control of Gene Expression,The University of Melbourne,epigenetics,1.000000
310,Entrepreneurship Strategy: From Ideation to Exit,HEC Paris,entrepreneurship-strategy,1.000000

Exportamos como csv

In [38]:
#df_coursera.to_csv('Coursera_merged.csv', index=False)